sudo: required
services:
- docker
language: java
jdk:
- oraclejdk9
branches:
  only:
  - master
before_install:
- mvn package
script:
  - docker build --tag saschazegerman/loginbuddy:latest .
after_success:
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push saschazegerman/loginbuddy:latest
env:
  matrix:
  - secure: ovlUA1xljm4L6FLm/6CNxyIuISlgHnRfZzpNQLdaYxqY9cJQeR32cLG3gJkY16iDQA97LSxBeiq4IiljQkzhBp1zkZ08+kgcku02O6ZNL5Wk/JZUTV2NUJttZbaxHQR1wTsm0JUvPwJ3naoE8ymqpuO5XWcRQf4Jn6fx/oNhg1/woA+eULHG/o3pN0xi+0/d51oy48jbtVCJO/E4Fijigu2W7zCTxn8xKmlgKjKNqtrvSOsCtc9+zHpTG0GZ7jM42lTH3Iy8ARzdJLSfYyyTNqW9rr59fN8re5MkkrEvO94OLf/IP2W9kpG5ZgmoRgl9ZZjLNuD/Aezn+sZ2eqNTNfF6LY+igg5KJg4H1k28htgssGEWtH4XEZ6qYld0blKHr2MPkmh/kILNn9s/LP9hP0AysvlZrCv6eKV7McTjZxRdaZ2tpdSF3h8jt/eGdxlNpkJoypUb9IKBi4taLx7l04txzHrM6jqKLg1gIS5OIxWj+fHpPbtQbtFN1I4zKTl5vkRQj+528TywJf+/dcSBS4GGsZqtPfYvV045MHhVNFMCacInjuy8X5QzlXgfX2XXeop6OBPknW3Vkh4jP2K0yXXvzANTUltG7qKc/yalC57Pw9U76NE7R3C8YWPKwst6YpjQUuR5YKKnWvBjDO1G4+uXZ6vMAGknRJnvtfc4mxc=
  - secure: RSzXznICnDi4Bv7yP2euMvx7popOHShdXOmY2D8C9gXxwbCTTMFgYye7n6hfLGhm4G7hRYZ+sApmfCeEYnl1AQdZXSwQXSHY/5lkiyyiLeupL8NSorhNn1t1OuPaLwSWoybrCAe0se3PKTBHz7XT68ICW6TwMFpd/7T6/2zVoQKE+lICZ4q3lT8nQovsSkWkt7v064DoSImWMGJQe6QfpihPUbSxNr99x+q+WuEgXhqYoXiB+O0O3tnJtxK/w7/gSnHlAYaBitqbIk819vAfu+e9ZkDRg1VysWsgTTcvo2Cf6q5V01WKiy/gdEfEwy/6zah9V5POUGtSSBNFSSnTPU/cuBZN8s9eM6do38PZkNgnh1d3J73TDagQRvU1/qkEOExDDA61XVX0k5Rg/8cCgMTHFcxnk8wxBIxkqrlrjfvKe2hexjfJQMP5nGqYXWI8fdsZA5kX4soc0c/Z35NkroL2wGkbdS+007laZX4M62Vgrx5XOBjDKKitfkVYDEj8f83TMdDWa8pcuibasWHpRInqnEhlrWunqf2vXLd8lvwM5nyDF/WTvZM+DijwVFWFXm9AuvEDSZBM3e4ay3NvivIatc8f/RMLB3LONMI5a6zuGyoIdajXT/ONEYimAapaTRXhl9Rab9XxDi8Ez/jl0R8YMRSoT0xA9jW8DwJox/c=
