sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk9

branches:
  only:
  - master

script:
  - mvn package

before_install:
  - docker build --tag saschazegerman/loginbuddy:latest .