#
# This docker compose file is usable for development purposes:
#
# NOTE: use this only for local development purposes!
#
# - it enables remote debugging
# - it enables JMX support#
#
version: '3.4'
services:
  loginbuddy-demosetup:
    build:
      context: .
      dockerfile: Dockerfile_demosetup
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "9010:9010"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,suspend=n,server=y -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"