#
# This docker compose file is usable for development purposes:
#
# NOTE: use this only for local development purposes!
#
version: '3.4'
services:
  loginbuddy-demosetup:
    image: saschazegerman/loginbuddy:latest-demo
    restart: always
    ports:
      - "80:80"
      - "443:443"